---
all:
  children:
    cluster:
      vars:
        # common connection opts
        ansible_user: root
        ansible_connection: docker
        become: true
        become_user: root

        # common cartridge opts
        cartridge_app_name: 'myapp'
        cartridge_cluster_cookie: secret-cookie

        cartridge_custom_steps:
          - name: 'check_files_removed'
            file: './tasks/check_files_removed.yml'

        cartridge_bootstrap_vshard: true
        cartridge_failover_params:
          mode: stateful
          state_provider: stateboard
          stateboard_params:
            uri: vm1:4001
            password: secret-stateboard

        cartridge_auth:
          enabled: true
          users:
            - username: tarantool
              password: tarantool-the-best
              fullname: Tarantool The Best
              email: tarantool@tarantool.org

        cartridge_app_config:
          section-1:
            body:
              key-1: value-1
              key-2: value-2

      # instances
      hosts:
        storage-1:
          config:
            advertise_uri: 'vm1:3101'
            http_port: 8101
            test_option: 1

        core-1:
          config:
            advertise_uri: 'vm1:3102'
            http_port: 8102

        core-2:
          config:
            advertise_uri: 'vm1:3103'
            http_port: 8103
          expelled: true

        storage-1-replica:
          config:
            advertise_uri: 'vm2:3201'
            http_port: 8201
            test_option: 2

        my-stateboard:
          config:
            listen: 0.0.0.0:4001
            password: secret-stateboard
          stateboard: true

      children:
        # group by hosts
        machine_1:
          vars:
            ansible_host: vm1
            cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

          hosts:
            storage-1:
            core-1:
            core-2:
            my-stateboard:

        machine_2:
          vars:
            ansible_host: vm2
            cartridge_package_path: ./packages/myapp-1.0.0-0.tar.gz

            cartridge_multiversion: true

            cartridge_run_dir: /opt/run
            cartridge_data_dir: /opt/data
            cartridge_memtx_dir_parent: /opt/memtx
            cartridge_vinyl_dir_parent: /opt/vinyl
            cartridge_wal_dir_parent: /opt/wal
            cartridge_conf_dir: /opt/conf.d
            cartridge_app_install_dir: /opt/install
            cartridge_app_instances_dir: /opt/instances
            cartridge_systemd_dir: /etc/systemd/system

          hosts:
            storage-1-replica:

        # group by replica sets
        storage_1_replicaset:
          hosts:
            storage-1:
            storage-1-replica:
          vars:
            replicaset_alias: storage-1
            failover_priority:
              - storage-1
              - storage-1-replica
            roles:
              - vshard-storage
            all_rw: true
            vshard_group: hot

        core_1_replicaset:
          hosts:
            core-1:

          vars:
            replicaset_alias: core-1
            roles:
              - app.roles.custom
              - failover-coordinator

        core_2_replicaset:
          hosts:
            core-2:

          vars:
            replicaset_alias: core-2
            roles:
              - app.roles.custom
