---

- name: 'Stop and disable instance systemd service'
  systemd:
    name: '{{ instance_info.systemd_service }}'
    state: stopped
    enabled: false

- name: 'Cleanup instance files'
  file:
    path: '{{ filepath }}'
    state: absent
  loop_control:
    loop_var: filepath
  with_items: "{{ instance_info.paths_to_remove_on_expel }}"
