---

- when: cartridge_eval_body is not none or cartridge_eval_file is not none
  block:
    - name: 'Set eval body'
      set_fact:
        eval_body: >-
          {{
            cartridge_eval_body
            if cartridge_eval_body is not none
            else lookup("file", cartridge_eval_file)
          }}

    - name: 'Eval code on instance'
      cartridge_eval:
        console_sock: '{{ eval_console_sock }}'
        body: '{{ eval_body }}'
        args: '{{ cartridge_eval_args }}'
      register: eval_res_register

    - name: 'Set "eval_res" fact'
      set_fact:
        eval_res: '{{ eval_res_register.fact | default(omit) }}'
