---

- name: 'Select one not expelled instance'
  cartridge_get_not_expelled_instance:
    facts: '{{ cached_facts.not_expelled_instance }}'
    play_hosts: '{{ play_hosts }}'
  run_once: true
  delegate_to: localhost
  become: false
  register: not_expelled_instance_res

- name: 'Set "not_expelled_instance" fact'
  set_fact:
    not_expelled_instance: '{{ not_expelled_instance_res.fact }}'
  run_once: true
  delegate_to: localhost
  become: false
