---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp
    cartridge_cluster_cookie: secret-cookie

    cartridge_multiversion: true

    cartridge_enable_tarantool_repo: false
    cartridge_configure_systemd_unit_files: false
    cartridge_configure_tmpfiles: false
    cartridge_install_tarantool_for_tgz: false
    cartridge_create_user_group_for_tgz: false

    cartridge_custom_scenarios:
      update_and_restart_instance:
        - update_instance
        - restart_instance
        - wait_instance_started

    cartridge_failover_params:
      mode: stateful
      state_provider: stateboard
      stateboard_params:
        uri: vm1:4001
        password: secret-stateboard

  # instances
  hosts:
    core-1:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    storage-1-leader:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

    storage-1-replica:
      config:
        advertise_uri: 'vm2:3201'
        http_port: 8201

    storage-1-replica-2:
      config:
        advertise_uri: 'vm2:3202'
        http_port: 8202

    storage-2-leader:
      config:
        advertise_uri: 'vm1:3103'
        http_port: 8103

    storage-2-replica:
      config:
        advertise_uri: 'vm2:3203'
        http_port: 8203

    my-stateboard:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        core-1:
        storage-1-leader:
        storage-2-leader:
        my-stateboard:

    machine_2:
      vars:
        ansible_host: vm2

      hosts:
        storage-1-replica:
        storage-2-replica:
        storage-1-replica-2:

    core_1_replicaset:
      hosts:
        core-1:
      vars:
        replicaset_alias: core-1
        roles:
          - vshard-router
          - failover-coordinator

    storage_1_replicaset:
      hosts:
        storage-1-leader:
        storage-1-replica:
        storage-1-replica-2:
      vars:
        replicaset_alias: storage-1
        failover_priority:
          - storage-1-leader
          - storage-1-replica-2
          - storage-1-replica
        roles:
          - vshard-storage

    storage_2_replicaset:
      hosts:
        storage-2-leader:
        storage-2-replica:
      vars:
        replicaset_alias: storage-2
        failover_priority:
          - storage-2-leader
          - storage-2-replica
        roles:
          - vshard-storage
