---

- name: Deploy cluster with myapp 4.0.0
  hosts: cluster
  roles:
    - ansible-cartridge
  become: true
  become_user: root
  gather_facts: false
  vars:
    cartridge_cluster_cookie: secret-cookie
    cartridge_enable_tarantool_repo: true
    cartridge_configure_systemd_unit_files: true
    cartridge_configure_tmpfiles: true
    cartridge_install_tarantool_for_tgz: true
    cartridge_create_user_group_for_tgz: true
    cartridge_package_path: ./packages/myapp-4.0.0-0-with-c-2.5.0.tar.gz
