---
all:
  vars:
    cartridge_app_name: myapp
    cartridge_cluster_cookie: secret-cookie

    cartridge_package_path: ./myapp-1.0.0-0.rpm

    cartridge_bootstrap_vshard: false

    # may be useful for vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_common_args: '-o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  hosts:  # instances
    storage-1:
      config:
        advertise_uri: '172.19.0.2:3301'
        http_port: 8181

    storage-1-replica:
      config:
        advertise_uri: '172.19.0.3:3301'
        http_port: 8191

  children:
    # group instances by machines
    machine_1:
      vars:
        ansible_host: 172.19.0.2
        ansible_user: vagrant

      hosts:
        storage-1:

    machine_2:
      vars:
        ansible_host: 172.19.0.3
        ansible_user: vagrant

      hosts:
        storage-1-replica:

    # group instances by replicasets
    replicaset_storage_1:
      hosts:
        storage-1:
        storage-1-replica:
      vars:
        replicaset_alias: storage-1
        failover_priority:
          - storage-1
          - storage-1-replica
        roles:
          - vshard-storage
