FROM centos:7

ARG TARANTOOL_BRANCH=1_10

RUN yum -y update
RUN yum install -y python3-pip

RUN set -x \
    && curl -s https://packagecloud.io/install/repositories/tarantool/${TARANTOOL_BRANCH}/script.rpm.sh | bash \
    && yum -y install tarantool

COPY requirements.txt /tmp/
RUN pip3 install --upgrade -r /tmp/requirements.txt
