---
- name: Stop and disable instance systemd service
  systemd:
    name: '{{ instance_systemd_service }}'
    state: stopped
    enabled: false
  tags: cartridge-replicasets

- name: Cleanup instance files
  file:
    path: '{{ filepath }}'
    state: absent
  with_items:
    - '{{ instance_conf_file }}'
    - '{{ instance_control_sock }}'
    - '{{ instance_work_dir }}'
  loop_control:
    loop_var: filepath
  tags: cartridge-replicasets
