---
- name: Get topology
  cartridge_current_topology:
    control_sock: /var/run/tarantool/{{ cartridge_app_name }}.{{ instance }}.control
  register: topology
  delegate_to: '{{ instance }}'
  tags: cartridge-replicasets

- name: Update current topology
  set_fact:
    current_topology: '{{ topology.meta.replicasets }}'
  when: topology.meta.replicasets | length > 0
  tags: cartridge-replicasets
