---
- name: Get instance info
  uri:
    url: 'http://{{ server_address }}:{{ instance.http_port }}/admin/api'
    method: POST
    body_format: json
    status_code: 200
    return_content: true
    body:
      query: |-
        query {
          servers{
            uri,
            replicaset { uuid },
            status
          }
        }
  register: response
  failed_when: |-
    not(
      response.status == 200
      and 'json' in response
      and 'data' in response.json
      and 'servers' in response.json.data
    )

- name: Append instance info to running_instances
  set_fact:
    running_instances: '{{ running_instances | combine({ instance.name: response.json.data.servers[0] }) }}'
