---
- name: Install RPM
  include_tasks: install_rpm.yml
  when: ansible_os_family == 'RedHat'
  args:
    apply:
      tags: cartridge-instances
  tags: cartridge-instances

- name: Install DEB
  include_tasks: install_deb.yml
  when: ansible_os_family == 'Debian'
  args:
    apply:
      tags: cartridge-instances
  tags: cartridge-instances
