---
- name: Create group
  group:
    name: "tarantool"

- name: Create user and add to group
  user:
    name: "tarantool"
    groups: "tarantool"
    append: yes

- name: Create userspace folders
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - {path: /usr/share/tarantool}
    - {path: "/var/run/tarantool"}
    - {path: "/etc/tarantool/conf.d"}
    - {path: "/etc/systemd/system"}
  any_errors_fatal: true

- name: Unpack TGZ
  unarchive:
    dest: "/usr/share/tarantool"
    src: "{{ cartridge_package_path }}"
    keep_newer: true
  any_errors_fatal: true
