---
- name: 'Join {{ instance.name }} to a replicaset'
  cartridge_join_replicas:
    instance: '{{ instance }}'
    instance_address: '{{ host_address }}'
    control_instance_address: '{{ control_instance_address }}'
    control_instance_port: '{{ control_instance_port }}'
  register: res
  until: not res.failed
  retries: 5
  delay: 5
