---
- name: Get current failover status
  uri:
    url: "{{ cartridge_admin_url }}/admin/api"
    method: POST
    body_format: json
    status_code: 200
    return_content: true
    url_username: admin
    url_password: '{{ cartridge_cluster_cookie }}'
    force_basic_auth: true
    body:
      query: |-
        query {
          cluster {
            failover
          }
        }
  register: failover
  retries: 3
  delay: 5
  until: |
    failover.status == 200
    and 'json' in failover
    and 'errors' not in failover.json
  delegate_to: localhost
  become: false
  run_once: true

- name: Change failover status if it's required
  uri:
    url: "{{ cartridge_admin_url }}/admin/api"
    method: POST
    body_format: json
    status_code: 200
    return_content: true
    url_username: admin
    url_password: '{{ cartridge_cluster_cookie }}'
    force_basic_auth: true
    body:
      query: |-
        mutation {
          enable_failover: cluster {
            failover(enabled: {{ 'true' if (cartridge_failover) else 'false' }} )
          }
        }
  register: enable_failover
  retries: 3
  delay: 5
  until: |
    enable_failover.status == 200
    and 'json' in enable_failover
    and 'errors' not in enable_failover.json
  changed_when: true
  when: failover.json.data.cluster.failover != cartridge_failover
  delegate_to: localhost
  become: false
  run_once: true
