---

# We should store scenario in separated variable to
# avoid conflicts between plays.
- name: 'Collect names of custom scenario steps'
  set_fact:
    scenario_steps_names: '{{ cartridge_scenario }}'
  when: cartridge_scenario is not none
  run_once: true
  delegate_to: localhost
  become: false

- run_once: true
  delegate_to: localhost
  become: false
  when: cartridge_scenario is none
  block:
    - name: 'Collect scenarios'
      set_fact:
        scenarios: "{{ cartridge_role_scenarios | combine(cartridge_custom_scenarios) }}"

    - name: 'Check scenario name'
      fail:
        msg: "Unknown scenario name '{{ cartridge_scenario_name }}'"
      when: cartridge_scenario_name not in scenarios

    - name: 'Collect names of scenario steps'
      set_fact:
        scenario_steps_names: "{{ scenarios[cartridge_scenario_name] }}"

- name: 'Collect tasks for scenario steps'
  cartridge_set_scenario_steps:
    scenario_steps_names: '{{ scenario_steps_names }}'
    role_path: '{{ role_path }}'
    custom_steps_dir: '{{ cartridge_custom_steps_dir }}'
    custom_steps: '{{ cartridge_custom_steps }}'
  run_once: true
  delegate_to: localhost
  become: false
