---
- name: 'Set {{ instance.name }} roles'
  cartridge_set_roles:
    instance: '{{ instance }}'
    instance_address: '{{ instance_address }}'
    control_instance_address: '{{ control_instance_address }}'
    control_instance_port: '{{ control_instance_port }}'
