---

- name: 'Set instance facts'
  set_fact:
    role_facts:

      # Common variables

      cartridge_app_name: '{{ cartridge_app_name }}'
      cartridge_cluster_cookie: '{{ cartridge_cluster_cookie }}'
      cartridge_not_save_cookie_in_app_config: '{{ cartridge_not_save_cookie_in_app_config }}'
      cartridge_remove_temporary_files: '{{ cartridge_remove_temporary_files }}'
      cartridge_ignore_split_brain: '{{ cartridge_ignore_split_brain }}'
      cartridge_paths_to_keep_on_cleanup: '{{ cartridge_paths_to_keep_on_cleanup }}'
      cartridge_paths_to_keep_on_restore: '{{ cartridge_paths_to_keep_on_restore }}'

      # Role scenario configuration

      cartridge_scenario: '{{ cartridge_scenario }}'
      cartridge_custom_steps_dir: '{{ cartridge_custom_steps_dir }}'
      cartridge_custom_steps: '{{ cartridge_custom_steps }}'

      cartridge_scenario_name: '{{ cartridge_scenario_name }}'
      cartridge_custom_scenarios: '{{ cartridge_custom_scenarios }}'
      cartridge_role_scenarios: '{{ cartridge_role_scenarios }}'

      # Application package configuration

      cartridge_package_path: '{{ cartridge_package_path }}'
      cartridge_enable_tarantool_repo: '{{ cartridge_enable_tarantool_repo }}'

      # TGZ specific configuration

      cartridge_multiversion: '{{ cartridge_multiversion }}'

      cartridge_install_tarantool_for_tgz: '{{ cartridge_install_tarantool_for_tgz }}'
      cartridge_create_user_group_for_tgz: '{{ cartridge_create_user_group_for_tgz }}'

      cartridge_app_user: '{{ cartridge_app_user }}'
      cartridge_app_group: '{{ cartridge_app_group }}'

      cartridge_data_dir: '{{ cartridge_data_dir }}'
      cartridge_memtx_dir_parent: '{{ cartridge_memtx_dir_parent }}'
      cartridge_vinyl_dir_parent: '{{ cartridge_vinyl_dir_parent }}'
      cartridge_wal_dir_parent: '{{ cartridge_wal_dir_parent }}'
      cartridge_run_dir: '{{ cartridge_run_dir }}'
      cartridge_conf_dir: '{{ cartridge_conf_dir }}'
      cartridge_app_install_dir: '{{ cartridge_app_install_dir }}'
      cartridge_app_instances_dir: '{{ cartridge_app_instances_dir }}'

      cartridge_configure_systemd_unit_files: '{{ cartridge_configure_systemd_unit_files }}'
      cartridge_systemd_dir: '{{ cartridge_systemd_dir }}'

      cartridge_configure_tmpfiles: '{{ cartridge_configure_tmpfiles }}'
      cartridge_tmpfiles_dir: '{{ cartridge_tmpfiles_dir }}'

      cartridge_keep_num_latest_dists: '{{ cartridge_keep_num_latest_dists }}'

      # Instances configuration

      cartridge_defaults: '{{ cartridge_defaults }}'
      config: '{{ config }}'
      cartridge_runtime_params: '{{ cartridge_runtime_params }}'
      zone: '{{ zone }}'
      cartridge_extra_env: '{{ cartridge_extra_env }}'

      restarted: '{{ restarted }}'
      expelled: '{{ expelled }}'
      disabled: '{{ disabled }}'
      stateboard: '{{ stateboard }}'

      instance_start_timeout: '{{ instance_start_timeout }}'
      instance_start_retries: '{{ instance_start_retries }}'
      instance_start_delay: '{{ instance_start_delay }}'

      cartridge_wait_buckets_discovery: '{{ cartridge_wait_buckets_discovery }}'

      instance_discover_buckets_timeout: '{{ instance_discover_buckets_timeout }}'
      instance_discover_buckets_retries: '{{ instance_discover_buckets_retries }}'
      instance_discover_buckets_delay: '{{ instance_discover_buckets_delay }}'

      allowed_members_states: '{{ allowed_members_states }}'
      wait_members_alive_retries: '{{ wait_members_alive_retries }}'
      wait_members_alive_delay: '{{ wait_members_alive_delay }}'

      # Replicasets configuration

      replicaset_alias: '{{ replicaset_alias }}'
      failover_priority: '{{ failover_priority }}'
      roles: '{{ roles }}'
      all_rw: '{{ all_rw }}'
      vshard_group: '{{ vshard_group }}'
      weight: '{{ weight }}'
      twophase_netbox_call_timeout: '{{ twophase_netbox_call_timeout }}'
      twophase_upload_config_timeout: '{{ twophase_upload_config_timeout }}'
      twophase_apply_config_timeout: '{{ twophase_apply_config_timeout }}'

      edit_topology_timeout: '{{ edit_topology_timeout }}'
      edit_topology_healthy_timeout: '{{ edit_topology_healthy_timeout }}'
      edit_topology_allow_missed_instances: '{{ edit_topology_allow_missed_instances }}'

      ## Cluster configuration

      cartridge_app_config: '{{ cartridge_app_config }}'
      cartridge_app_config_path: '{{ cartridge_app_config_path }}'
      cartridge_app_config_upload_mode: '{{ cartridge_app_config_upload_mode }}'
      cartridge_app_config_upload_url: '{{ cartridge_app_config_upload_url }}'
      cartridge_tdg_token: '{{ cartridge_tdg_token }}'

      cartridge_auth: '{{ cartridge_auth }}'
      cartridge_bootstrap_vshard: '{{ cartridge_bootstrap_vshard }}'
      cartridge_failover: '{{ cartridge_failover }}'
      cartridge_failover_params: '{{ cartridge_failover_params }}'
      cartridge_failover_promote_params: '{{ cartridge_failover_promote_params }}'

      connect_to_membership_retries: '{{ connect_to_membership_retries }}'
      connect_to_membership_delay: '{{ connect_to_membership_delay }}'

      bootstrap_vshard_retries: '{{ bootstrap_vshard_retries }}'
      bootstrap_vshard_delay: '{{ bootstrap_vshard_delay }}'

      allow_warning_issues: '{{ allow_warning_issues }}'
      show_issues: '{{ show_issues }}'
      wait_cluster_has_no_issues_retries: '{{ wait_cluster_has_no_issues_retries }}'
      wait_cluster_has_no_issues_delay: '{{ wait_cluster_has_no_issues_delay }}'

      # Internal role facts that can be set by the user

      cartridge_delivered_package_path: '{{ cartridge_delivered_package_path }}'
      cartridge_control_instance: '{{ cartridge_control_instance }}'

      # Cross-step facts (for correct 'tasks_from' option usage)

      delivered_package_path: '{{ delivered_package_path }}'
      control_instance: '{{ control_instance }}'
      temporary_files: '{{ temporary_files }}'
      needs_restart: '{{ needs_restart }}'
      cluster_disabled_instances: '{{ cluster_disabled_instances }}'
      inventory_disabled_instances: '{{ inventory_disabled_instances }}'
      alive_not_expelled_instance: '{{ alive_not_expelled_instance }}'
      instance_backup_files: '{{ instance_backup_files }}'
      backup_archive_path: '{{ backup_archive_path }}'
      fetched_backup_archive_path: '{{ fetched_backup_archive_path }}'
      backup_files_from_machine: '{{ backup_files_from_machine }}'

      # Temp facts

      cached_facts_res: '{{ cached_facts_res }}'
      cached_facts: '{{ cached_facts }}'
      facts_for_machines_res: '{{ facts_for_machines_res }}'
      single_instances_for_each_machine: '{{ single_instances_for_each_machine }}'
      instances_from_same_machine: '{{ instances_from_same_machine }}'

      # Eval params

      cartridge_eval_file: '{{ cartridge_eval_file }}'
      cartridge_eval_body: '{{ cartridge_eval_body }}'
      cartridge_eval_args: '{{ cartridge_eval_args }}'
      cartridge_eval_with_retries: '{{ cartridge_eval_with_retries }}'
      cartridge_eval_retries: '{{ cartridge_eval_retries }}'
      cartridge_eval_delay: '{{ cartridge_eval_delay }}'

      # Backups params

      cartridge_remote_backups_dir: '{{ cartridge_remote_backups_dir }}'
      cartridge_fetch_backups: '{{ cartridge_fetch_backups }}'
      cartridge_fetch_backups_dir: '{{ cartridge_fetch_backups_dir }}'
      cartridge_restore_backup_path: '{{ cartridge_restore_backup_path }}'
      cartridge_force_restore: '{{ cartridge_force_restore }}'
      cartridge_ignore_alien_backup: '{{ cartridge_ignore_alien_backup }}'

      # Edit topology check

      cartridge_force_advertise_uris_change: '{{ cartridge_force_advertise_uris_change }}'
      cartridge_ignore_extra_cluster_instances: '{{ cartridge_ignore_extra_cluster_instances }}'
      cartridge_ignore_extra_cluster_replicasets: '{{ cartridge_ignore_extra_cluster_replicasets }}'
      cartridge_ignore_renamed_replicasets: '{{ cartridge_ignore_renamed_replicasets }}'
