---
- name: 'Set {{ instance.name }} role'
  uri:
    url: 'http://{{ server_address }}:{{ instance.http_port }}/admin/api'
    method: POST
    body_format: json
    status_code: 200
    return_content: true
    body:
      query: |-
        mutation {
          join_server(
            uri: "{{ running_instances[instance.name].uri }}",
            roles: [{% for role in instance.roles %} "{{ role }}",{%endfor%}]
          )
        }
  register: response
  failed_when: |-
    not(
      response.status == 200
      and 'json' in response
      and 'data' in response.json
      and 'join_server' in response.json.data
      and response.json.data.join_server
    )

  when: |-
    instance.roles is defined
    and instance.name in running_instances
    and running_instances[instance.name].status == 'unconfigured'
