---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp
    cartridge_cluster_cookie: secret-cookie
    cartridge_custom_steps_dir: './custom_steps'
    cartridge_custom_scenarios:
      custom_scenario:
        - custom_step

  hosts:
    storage-1:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

  children:
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        storage-1:
