---

- name: 'Check that instance is not running'
  cartridge_check_instance_not_running:
    console_sock: '{{ instance_info.console_sock }}'
  register: check_instance_not_running_res

- name: 'Cleanup instance files'
  file:
    path: '{{ file_path }}'
    state: absent
  loop_control:
    loop_var: file_path
  with_items: '{{ instance_info.files_to_remove_on_cleanup }}'

- name: 'Find data to remove from instance directories'
  find:
    file_type: any
    hidden: true
    paths: '{{ instance_info.dirs_to_remove_on_cleanup }}'
    excludes: '{{ ["config", ".tarantool.cookie"] + cartridge_paths_to_keep_on_cleanup }}'
  register: paths_to_remove_on_cleanup

- name: 'Cleanup instance directories'
  file:
    path: '{{ file.path }}'
    state: absent
  loop_control:
    label: '{{ file.path }}'
    loop_var: file
  with_items: '{{ paths_to_remove_on_cleanup.files }}'
