---

- when: cartridge_auth is not none
  tags: cartridge-config
  block:
    - name: 'BLOCK: Select control instance'
      include_tasks: 'blocks/set_control_instance.yml'
      run_once: true
      when: not control_instance

    - name: 'Configure cartridge auth'
      cartridge_configure_auth:
        auth: '{{ cartridge_auth }}'
        console_sock: '{{ control_instance.console_sock }}'
      run_once: true
      delegate_to: '{{ control_instance.name }}'
