---
- tags:
    - cartridge-config
  when: cartridge_eval_body is not none or cartridge_eval_file is not none

  block:
    - name: 'BLOCK: Select control instance'
      include_tasks: 'blocks/set_control_instance.yml'
      run_once: true
      when: not control_instance

    - name: 'Set eval body'
      set_fact:
        eval_body: >-
          {{
            cartridge_eval_body
            if cartridge_eval_body is not none
            else lookup("file", cartridge_eval_file)
          }}
      run_once: true
      delegate_to: '{{ control_instance.name }}'

    - name: 'Eval code on control instance {{ control_instance.name }}'
      cartridge_eval:
        console_sock: '{{ control_instance.console_sock }}'
        body: '{{ eval_body }}'
        args: '{{ cartridge_eval_args }}'
      register: eval_res_register
      run_once: true
      delegate_to: '{{ control_instance.name }}'

    - name: 'Set "eval_res" fact'
      set_fact:
        eval_res: '{{ eval_res_register.fact | default(omit) }}'
      run_once: true
      delegate_to: '{{ control_instance.name }}'
