---

- tags:
    - cartridge-config
  block:
    - name: 'BLOCK: Select control instance'
      include_tasks: 'blocks/set_control_instance.yml'
      run_once: true
      when: not control_instance

    - name: 'Force leaders via {{ control_instance.name }}'
      cartridge_failover_promote:
        promote_play_hosts: true
        module_hostvars: '{{ cached_facts.failover_promote }}'
        cluster_disabled_instances: '{{ cluster_disabled_instances }}'
        play_hosts: '{{ play_hosts }}'
        failover_promote_params: '{{ cartridge_failover_promote_params }}'
        console_sock: '{{ control_instance.console_sock }}'
        netbox_call_timeout: '{{ twophase_netbox_call_timeout }}'
        upload_config_timeout: '{{ twophase_upload_config_timeout }}'
        apply_config_timeout: '{{ twophase_apply_config_timeout }}'
      run_once: true
      delegate_to: '{{ control_instance.name }}'
