---

- name: 'Restart instance systemd service'
  systemd:
    name: '{{ instance_info.systemd_service }}'
    state: restarted
    enabled: true
  when: (restarted) or (restarted is none and needs_restart)
  tags: cartridge-instances
