---

- name: 'Restore instance from archive'
  cartridge_restore_instance:
    console_sock: '{{ instance_info.console_sock }}'
    restore_archive_path: '{{ cartridge_restore_archive_path }}'
    remote_backups_dir: '{{ cartridge_remote_backups_dir }}'
    instance_id: '{{ instance_info.instance_id }}'
    force_restore: '{{ cartridge_force_restore }}'
