---

- name: 'Restart instance systemd service'
  systemd:
    name: '{{ instance_info.systemd_service }}'
    state: restarted
    enabled: true
  when: (restarted is not none and restarted) or (needs_restart is defined and needs_restart)
  tags: cartridge-instances
