---

- tags: cartridge-instances
  block:
    - name: 'BLOCK : Install package'
      include_tasks: 'blocks/update_package.yml'
      when:
        - inventory_hostname in single_instances_for_each_machine
        - delivered_package_path is not none

    - name: 'Check if instance restart is required to use new package'
      cartridge_get_needs_restart:
        instance_info: '{{ instance_info }}'
        check_package_updated: true
      when:
        - not cartridge_multiversion
        - not expelled
        - restarted is none
        - not needs_restart
      register: needs_restart_res

    - name: 'Set "needs_restart" fact'
      set_fact:
        needs_restart: '{{ needs_restart_res.fact }}'
      when: "'fact' in needs_restart_res"
