---

- run_once: true
  delegate_to: '{{ control_instance.name }}'
  when: cartridge_app_config_path is not none
  tags: cartridge-config
  block:
    - name: 'Copy application config on remote host'
      any_errors_fatal: true
      copy:
        src: '{{ cartridge_app_config_path }}'
        dest: '/tmp/'

    - name: 'Apply application config'
      cartridge_apply_app_config:
        local_config_path: '{{ cartridge_app_config_path }}'
        remote_dir: '/tmp/'
        upload_endpoint: '{{ cartridge_app_config_upload_endpoint }}'
        console_sock: '{{ control_instance.console_sock }}'
        http_port: '{{ app_config_upload_http_port }}'
        cluster_cookie: '{{ cartridge_cluster_cookie }}'
        tdg_token: '{{ cartridge_tdg_token }}'
      register: apply_app_config_res

    - name: 'Add uploaded config to "temporary_files" fact'
      set_fact:
        temporary_files: "{{ temporary_files + [apply_app_config_res.fact.dest_path] }}"
