---

- tags:
    - cartridge-instances
    - cartridge-replicasets
    - cartridge-config
  block:
    - name: 'BLOCK: Select control instance'
      include_tasks: 'blocks/set_control_instance.yml'
      run_once: true
      when: not control_instance

    - name: 'Wait until cluster has no issues'
      cartridge_check_cluster_issues:
        allow_warnings: '{{ allow_warning_issues }}'
        show_issues: '{{ show_issues }}'
        console_sock: '{{ control_instance.console_sock }}'
      register: cluster_issues_res
      until: not cluster_issues_res.failed
      retries: '{{ wait_cluster_has_no_issues_retries }}'
      delay: '{{ wait_cluster_has_no_issues_delay }}'
      run_once: true
      delegate_to: '{{ control_instance.name }}'
