---

- name: 'Wait for the instance to start and discover buckets'
  cartridge_check_instance_state:
    console_sock: '{{ instance_info.console_sock }}'
    stateboard: '{{ stateboard }}'
    check_buckets_are_discovered: '{{ cartridge_wait_buckets_discovery }}'
  register: check_instance
  until: not check_instance.failed
  retries: '{{
      instance_start_timeout // instance_start_delay
      if instance_start_timeout is not none
      else instance_start_retries
    }}'
  delay: '{{ instance_start_delay }}'
  when: not expelled
  tags: cartridge-instances
