---

- name: 'Check that all backup steps fail on non-joined instance'
  hosts: instance-1-not-joined
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_tasks: include/check_box_cfg_not_called.yml
      loop_control:
        loop_var: backup_step
      with_items:
        - backup
        - backup_start
        - backup_stop

- name: 'Backup joined instances and stateboard without fetching archive'
  hosts: cluster:!instance-1-not-joined
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_tasks: include/check_backup.yml

    - name: Check that fetching archive was skipped
      assert:
        fail_msg: 'Fetching archive should be skipped'
        success_msg: 'Fetching archive was skipped'
        that: backup_archive_fetch_res.skipped

    - name: 'Check fetched_backup_archive_path fact is empty'
      assert:
        fail_msg: 'Received bad fetched_backup_archive_path'
        success_msg: 'Received fetched_backup_archive_path is OK'
        that: fetched_backup_archive_path is none

- name: 'Backup joined instances and stateboard with fetching archive'
  hosts: cluster:!instance-1-not-joined
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_tasks: include/check_backup.yml
      vars:
        cartridge_fetch_backups: true

    - name: Check that fetching archive wasn't skipped
      assert:
        fail_msg: 'Fetching archive should not be skipped'
        success_msg: 'Fetching archive was not skipped'
        that: backup_archive_fetch_res.changed

    - name: 'Check fetched_backup_archive_path fact'
      assert:
        fail_msg: 'Received bad fetched_backup_archive_path'
        success_msg: 'Received fetched_backup_archive_path is OK'
        that: >-
          fetched_backup_archive_path ==
            (playbook_dir, cartridge_fetch_backups_dir, backup_archive_path | basename) | cartridge_path_join

- name: 'Check backup start and stop for joined instances and stateboard'
  hosts: cluster:!instance-1-not-joined
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_tasks: include/check_backup_start_stop.yml
