---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp
    cartridge_package_path: ./packages/myapp-1.0.0-0.tar.gz
    cartridge_multiversion: true

    cartridge_data_dir: /opt/data
    cartridge_memtx_dir_parent: /opt/memtx
    cartridge_vinyl_dir_parent: /opt/vinyl
    cartridge_wal_dir_parent: /opt/wal

    cartridge_run_dir: /opt/run
    cartridge_conf_dir: /opt/conf.d
    cartridge_app_install_dir: /opt/install
    cartridge_app_instances_dir: /opt/instances
    cartridge_systemd_dir: /etc/systemd/system

  # instances
  hosts:
    instance-1-not-joined:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    instance-2-joined:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

    my-stateboard:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        instance-1-not-joined:
        instance-2-joined:
        my-stateboard:

    storage_1_replicaset:
      hosts:
        instance-2-joined:
      vars:
        replicaset_alias: rpl-1
        roles:
          - failover-coordinator
          - app.roles.custom
