- name: 'Debug upload result'
  debug:
    msg: '{{ apply_app_config_res }}'
  run_once: true

- name: 'Debug config section'
  debug:
    msg: '{{ eval_res }}'
  run_once: true

- name: 'Check config section'
  assert:
    fail_msg: 'Config section has incorrect body'
    success_msg: 'Config section has correct body'
    that: eval_res[0] == expected_test_section
  run_once: true
