---

- name: 'Move instance'
  hosts: cluster
  become: true
  become_user: root
  gather_facts: false
  vars:
    cartridge_cluster_cookie: secret-cookie
  tasks:
    # Backup files without fetching archive

    - name: 'Call backup files'
      import_role:
        name: ansible-cartridge
      vars:
        cartridge_fetch_backups: false
        cartridge_scenario:
          - stop_instance
          - backup_files

    - name: 'Check that fetching archive was skipped'
      assert:
        fail_msg: 'Fetching archive should be skipped'
        success_msg: 'Fetching archive was skipped'
        that: backup_archive_fetch_res.skipped

    - name: 'Check fetched_backup_archive_path fact is empty'
      assert:
        fail_msg: 'Received bad fetched_backup_archive_path'
        success_msg: 'Received fetched_backup_archive_path is OK'
        that: fetched_backup_archive_path is none

    # Backup files with fetching archive

    - name: 'Call backup files'
      import_role:
        name: ansible-cartridge
      vars:
        cartridge_fetch_backups: true
        cartridge_scenario:
          - stop_instance
          - backup_files

    - name: "Check that fetching archive wasn't skipped"
      assert:
        fail_msg: 'Fetching archive should not be skipped'
        success_msg: 'Fetching archive was not skipped'
        that: backup_archive_fetch_res.changed

    - name: 'Check fetched_backup_archive_path fact'
      assert:
        fail_msg: 'Received bad fetched_backup_archive_path'
        success_msg: 'Received fetched_backup_archive_path is OK'
        that: >-
          fetched_backup_archive_path ==
            (playbook_dir, cartridge_fetch_backups_dir, backup_archive_path | basename) | cartridge_path_join

    # Change ansible host

    - name: 'Change ansible host of all instances'
      set_fact:
        ansible_host: vm2
        config:
          advertise_uri: 'vm2:{{ binary_port }}'
          http_port: '{{ http_port }}'
        cartridge_restore_backup_path_local: '{{ fetched_backup_archive_path }}'
      when: not stateboard

    - name: 'Change ansible host of stateboard'
      set_fact:
        ansible_host: vm2
        cartridge_restore_backup_path_local: '{{ fetched_backup_archive_path }}'
      when: stateboard

    # Restore joined instances and stateboard

    - name: 'Call restore from folder'
      vars:
        cartridge_restore_backup_path_local: '{{ fetched_backup_archive_path }}'
        cartridge_force_advertise_uris_change: true
        cartridge_defaults:
          replication_connect_quorum: 0
        cartridge_scenario:
          - deliver_package
          - update_package
          - stop_instance
          - restore
          - update_instance
          - configure_instance
          - start_instance
          - wait_instance_started
      import_role:
        name: ansible-cartridge

- name: 'Check instances'
  hosts: instance-2-joined,instance-3-joined
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: 'Check tuples'
      vars:
        cartridge_eval_args: '{{ check_restore_eval_args }}'
        cartridge_eval_body: '{{ check_restore_eval_body }}'
        cartridge_scenario:
          - eval
      import_role:
        name: ansible-cartridge
