---

- name: 'Change URI of core-1 instance to make 5 instances in membership'
  hosts: core-1-replica
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: 'Set new advertise_uri in inventory'
      set_fact:
        config:
          advertise_uri: 'vm1:3305'
          http_port: 8105

    - vars:
        cartridge_force_advertise_uris_change: true
        cartridge_scenario:
          - configure_instance
          - restart_instance
          - wait_instance_started
          - connect_to_membership
          - edit_topology
      import_role:
        name: ansible-cartridge

- name: 'Edit topology check for all cluster'
  hosts: cluster
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - import_role:
        name: ansible-cartridge

- name: 'Edit topology check for one replicaset'
  hosts: core_1_replicaset
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - import_role:
        name: ansible-cartridge

- name: 'Edit topology check for one instance'
  hosts: core-1
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - import_role:
        name: ansible-cartridge

- name: 'Remove core-2 instance and core-rs-2 replicaset in inventory'
  hosts: core-2,core_2_replicaset
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: 'Remove instance specific facts in inventory'
      set_fact:
        config: null
        replicaset_alias: null
        failover_priority: null
        roles: null

- name: 'Rename core_1_replicaset replicaset in inventory'
  hosts: core_1_replicaset
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: 'Set new alias in inventory'
      set_fact:
        replicaset_alias: core-rs-1-renamed

- name: 'Change URI of core-1 instance in inventory'
  hosts: core-1-replica
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: 'Set new advertise_uri in inventory'
      set_fact:
        config:
          advertise_uri: 'vm1:3306'
          http_port: 8106

- name: 'Edit topology check for all cluster'
  hosts: cluster
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - ignore_errors: true
      import_role:
        name: ansible-cartridge

    - name: 'Show check result'
      debug:
        var: edit_topology_check_res

    - name: 'Check that edit topology check message is correct'
      assert:
        that: >-
          edit_topology_check_res.msg == (
            "Found dangerous changes: "
            "some instances from cluster are missing in inventory: core-2, core-2-replica; "
            "advertise uris of some instances changed: core-1-replica (vm1:3305 -> vm1:3306); "
            "some replicasets from cluster are missing in inventory: core-rs-2; "
            "looks like that some replicasets should be renamed in inventory: core-rs-1-renamed -> core-rs-1. "
            "You can disable these checks with the appropriate flags (see 'edit_topology' step documentation)."
          )
        fail_msg: 'Edit topology check message is incorrect'
        success_msg: 'Edit topology check message is correct'

- name: 'Edit topology check for one replicaset'
  hosts: core_1_replicaset
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - ignore_errors: true
      import_role:
        name: ansible-cartridge

    - name: 'Show check result'
      debug:
        var: edit_topology_check_res

    - name: 'Check that edit topology check message is correct'
      assert:
        that: >-
          edit_topology_check_res.msg == (
            "Found dangerous changes: "
            "some instances from cluster are missing in inventory: core-2, core-2-replica; "
            "advertise uris of some instances changed: core-1-replica (vm1:3305 -> vm1:3306); "
            "some replicasets from cluster are missing in inventory: core-rs-2; "
            "looks like that some replicasets should be renamed in inventory: core-rs-1-renamed -> core-rs-1. "
            "You can disable these checks with the appropriate flags (see 'edit_topology' step documentation)."
          )
        fail_msg: 'Edit topology check message is incorrect'
        success_msg: 'Edit topology check message is correct'

- name: 'Edit topology check for one instance'
  hosts: core-1
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - ignore_errors: true
      import_role:
        name: ansible-cartridge

    - name: 'Show check result'
      debug:
        var: edit_topology_check_res

    - name: 'Check that edit topology check message is correct'
      assert:
        that: >-
          edit_topology_check_res.msg == (
            "Found dangerous changes: "
            "some instances from cluster are missing in inventory: core-2, core-2-replica; "
            "some replicasets from cluster are missing in inventory: core-rs-2; "
            "looks like that some replicasets should be renamed in inventory: core-rs-1-renamed -> core-rs-1. "
            "You can disable these checks with the appropriate flags (see 'edit_topology' step documentation)."
          )
        fail_msg: 'Edit topology check message is incorrect'
        success_msg: 'Edit topology check message is correct'

- name: 'Edit topology check for all cluster with ignore flags'
  hosts: core_1_replicaset
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - vars:
        cartridge_force_advertise_uris_change: true
        cartridge_ignore_extra_cluster_instances: true
        cartridge_ignore_extra_cluster_replicasets: true
        cartridge_ignore_renamed_replicasets: true
      import_role:
        name: ansible-cartridge
