---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp

    cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

    cartridge_failover_params:
      mode: stateful
      state_provider: stateboard
      stateboard_params:
        uri: vm1:4001
        password: secret-stateboard

    wait_members_alive_timeout: 2
    wait_members_alive_delay: 1

    wait_cluster_has_no_issues_timeout: 2
    wait_cluster_has_no_issues_delay: 1

  # instances
  hosts:
    instance-1:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    instance-2-joined:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

    instance-3-joined:
      config:
        advertise_uri: 'vm1:3103'
        http_port: 8103

    instance-4:
      config:
        advertise_uri: 'vm1:3104'
        http_port: 8104

    instance-5-not-joined:
      config:
        advertise_uri: 'vm1:3105'
        http_port: 8105

    instance-6-joined:
      config:
        advertise_uri: 'vm1:3106'
        http_port: 8106

    my-stateboard:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        instance-1:
        instance-2-joined:
        instance-3-joined:
        instance-4:
        instance-5-not-joined:
        instance-6-joined:
        my-stateboard:

    # group by replica sets
    replicaset_1:
      hosts:
        instance-2-joined:
        instance-3-joined:
        instance-5-not-joined:
        instance-6-joined:

      vars:
        replicaset_alias: r-1
        roles:
          - app.roles.custom
          - failover-coordinator
