---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp
    cartridge_cluster_cookie: secret-cookie

    cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

    cartridge_bootstrap_vshard: true

    cartridge_failover_params:
      mode: stateful
      state_provider: stateboard
      stateboard_params:
        uri: vm1:4001
        password: secret-stateboard

  # instances
  hosts:
    storage-1-leader:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    storage-1-replica:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

    my-stateboard:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        storage-1-leader:
        storage-1-replica:
        my-stateboard:

    storage_1_replicaset:
      hosts:
        storage-1-leader:
        storage-1-replica:
      vars:
        replicaset_alias: storage-1
        failover_priority:
          - storage-1-leader
          - storage-1-replica
        roles:
          - vshard-storage
        vshard_group: hot
