---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp
    cartridge_cluster_cookie: secret-cookie

  # instances
  hosts:
    instance-rpm-1:
      config:
        advertise_uri: 'vm1:3101'

    instance-rpm-2:
      config:
        advertise_uri: 'vm1:3102'

    instance-rpm-expelled:
      config:
        advertise_uri: 'vm1:3103'
      expelled: true

    instance-rpm-restarted-is-set:
      config:
        advertise_uri: 'vm1:3104'
      restarted: true

    my-stateboard-rpm:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

    instance-tgz-1:
      config:
        advertise_uri: 'vm2:3101'

    instance-tgz-2:
      config:
        advertise_uri: 'vm2:3102'

    instance-tgz-expelled:
      config:
        advertise_uri: 'vm2:3103'
      expelled: true

    instance-tgz-restarted-is-set:
      config:
        advertise_uri: 'vm2:3104'
      restarted: true

    my-stateboard-tgz:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1
        cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

      hosts:
        instance-rpm-1:
        instance-rpm-2:
        instance-rpm-expelled:
        instance-rpm-restarted-is-set:
        my-stateboard-rpm:

    machine_2:
      vars:
        ansible_host: vm2
        cartridge_package_path: ./packages/myapp-1.0.0-0.tar.gz
        cartridge_multiversion: true

      hosts:
        instance-tgz-1:
        instance-tgz-2:
        instance-tgz-expelled:
        instance-tgz-restarted-is-set:
        my-stateboard-tgz:
