---

all:
  children:
    cluster:
      vars:
        # common connection opts
        ansible_user: root
        ansible_connection: docker
        become: true
        become_user: root

        # common cartridge opts
        cartridge_app_name: myapp
        cartridge_cluster_cookie: secret-cookie
        cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

        cartridge_bootstrap_vshard: true

        cartridge_defaults:
          log_level: 5

      # instances
      hosts:
        core-1:
          config:
            advertise_uri: 'vm1:3301'
            http_port: 8101
            memtx_memory: 33554432  # 32 Mb

        core-1-replica:
          config:
            advertise_uri: 'vm1:3302'
            memtx_memory: 33554432  # 32 Mb

      children:
        # group by hosts
        machine_1:
          vars:
            ansible_host: vm1

          hosts:
            core-1:
            core-1-replica:

        # group by replica sets
        core_1_replicaset:
          hosts:
            core-1:
            core-1-replica:
          vars:
            replicaset_alias: core-1
            failover_priority:
              - core-1
              - core-1-replica
            roles:
              - app.roles.custom
              - vshard-router
              - failover-coordinator
