---

all:
  children:
    cluster:
      vars:
        ansible_user: root
        ansible_connection: docker
        become: true
        become_user: root

        cartridge_app_name: myapp
        cartridge_cluster_cookie: secret-cookie
        cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

        cartridge_bootstrap_vshard: true

        cartridge_control_instance:
          console_sock: "/var/run/tarantool/myapp.core-1.control"
          http_port: 8101
          name: "core-1"

      hosts:
        core-1:
          config:
            advertise_uri: 'vm1:3301'
            http_port: 8101

        core-1-replica:
          config:
            advertise_uri: 'vm1:3302'
            http_port: 8102

        core-2:
          config:
            advertise_uri: 'vm1:3303'
            http_port: 8103

        core-2-replica:
          config:
            advertise_uri: 'vm1:3304'
            http_port: 8104

      children:
        machine_1:
          vars:
            ansible_host: vm1

          hosts:
            core-1:
            core-1-replica:
            core-2:
            core-2-replica:

        core_1_replicaset:
          hosts:
            core-1:
            core-1-replica:
          vars:
            replicaset_alias: core-rs-1
            failover_priority:
              - core-1
              - core-1-replica
            roles:
              - app.roles.custom
              - vshard-router
              - failover-coordinator

        core_2_replicaset:
          hosts:
            core-2:
            core-2-replica:
          vars:
            replicaset_alias: core-rs-2
            failover_priority:
              - core-2
              - core-2-replica
            roles:
              - app.roles.custom
              - vshard-router
              - failover-coordinator
