---
all:
  children:
    cluster:
      vars:
        # common connection opts
        ansible_user: root
        ansible_connection: docker
        become: true
        become_user: root

        # common cartridge opts
        cartridge_app_name: myapp
        cartridge_cluster_cookie: secret-cookie
        cartridge_defaults:
          some_option: 'default value'

        cartridge_bootstrap_vshard: true
        cartridge_failover_params:
          mode: stateful
          state_provider: stateboard
          stateboard_params:
            uri: vm1:3310
            password: secret-stateboard

        cartridge_auth:
          enabled: true

          cookie_max_age: 1000
          cookie_renew_age: 100

          users:
            - username: tarantool
              password: tarantool-the-best
              fullname: Tarantool The Best
              email: tarantool@tarantool.org

        cartridge_app_config:
          section-1:
            body:
              key-1: value-1
              key-2: value-2

          section-2:
            body: section-2-value

          section-3:
            deleted: true

      # instances
      hosts:
        storage-1:
          config:
            advertise_uri: 'vm1:3301'
            http_port: 8081

        storage-1-replica:
          config:
            advertise_uri: 'vm1:3302'
            http_port: 8082

        storage-1-replica-2:
          config:
            advertise_uri: 'vm2:3312'
            http_port: 8092

        core-1:
          config:
            advertise_uri: 'vm2:3311'
            http_port: 8091
            memtx_memory: 268436000
          instance_start_timeout: 120

        core-2:
          config:
            advertise_uri: 'vm1:3303'
            http_port: 8083
          expelled: true

        my-stateboard:
          config:
            listen: vm1:3310
            password: secret-stateboard
          stateboard: true

      children:
        # group by hosts
        host1:
          vars:
            ansible_host: vm1
            cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

          hosts:
            storage-1:
            storage-1-replica:
            core-2:
            my-stateboard:

        host2:
          vars:
            ansible_host: vm2
            cartridge_package_path: ./packages/myapp-1.0.0-0.deb

          hosts:
            core-1:
            storage-1-replica-2:

        # group by replica sets
        storage_1_replicaset:
          hosts:
            storage-1:
            storage-1-replica:
            storage-1-replica-2:
          vars:
            replicaset_alias: storage-1
            failover_priority:
              - storage-1
              - storage-1-replica
              - storage-1-replica-2
            roles:
              - 'vshard-storage'
            weight: 3
            all_rw: true
            vshard_group: hot

        core_1_replicaset:
          hosts:
            core-1:

          vars:
            replicaset_alias: core-1
            roles:
              - app.roles.custom
              - vshard-router
              - failover-coordinator

        core_2_replicaset:
          hosts:
            core-2:

          vars:
            replicaset_alias: core-2
            roles:
              - 'app.roles.custom'
