---
all:
  children:
    cluster:
      vars:
        cartridge_app_name: myapp
        cartridge_package_path: ./myapp-1.0.0-0.rpm
        cartridge_cluster_cookie: secret-cookie
        cartridge_defaults:
          log_level: 1

        cartridge_bootstrap_vshard: true
        cartridge_failover: true

        cartridge_auth:
          enabled: true

          cookie_max_age: 1000
          cookie_renew_age: 100

          users:
            - username: tarantool
              password: tarantool-the-best
              fullname: Tarantool The Best
              email: tarantool@tarantool.org

        cartridge_app_config:
          section-1:
            body:
              key-1: value-1
              key-2: value-2

          section-2:
            body: section-2-value

          section-3:
            deleted: true

      children:
        storage_1_replicaset:
          hosts:
            storage-1:
            storage-1-replica:
            storage-1-replica-2:
          vars:
            replicaset_alias: storage-1
            leader: storage-1
            roles:
              - 'vshard-storage'

        core_1_replicaset:
          hosts:
            core-1:

          vars:
            replicaset_alias: core-1
            leader: core-1
            roles:
              - 'app.roles.custom'
              - 'vshard-router'

        core_2_replicaset:
          hosts:
            core-2:

          vars:
            replicaset_alias: core-2
            leader: core-2
            roles:
              - 'app.roles.custom'

        host1:
          vars:
            ansible_host: vm1
            ansible_user: root
            ansible_connection: docker
            become: true
            become_user: root

          hosts:
            storage-1:
              config:
                advertise_uri: 'vm1:3301'
                http_port: 8081

            storage-1-replica:
              config:
                advertise_uri: 'vm1:3302'
                http_port: 8082

            core-2:
              config:
                advertise_uri: 'vm1:3303'
                http_port: 8083
              expelled: true

        host2:
          vars:
            ansible_host: vm2
            ansible_user: root
            ansible_connection: docker
            become: true
            become_user: root

          hosts:
            core-1:
              config:
                advertise_uri: 'vm2:3311'
                http_port: 8091
                memtx_memory: 268436000

            storage-1-replica-2:
              config:
                advertise_uri: 'vm2:3312'
                http_port: 8092
