---
all:
  vars:
    cartridge_package_path: ./myapp-1.0.0-0.rpm
    # cartridge_app_name: myapp
    cartridge_cluster_cookie: new-cookie

    cartridge_defaults:
      log_level: 4

  children:
    cluster:
      children:
        instances:
          children:
            host1:
              vars:
                ansible_host: vm1
                ansible_user: root
                ansible_connection: docker
                become: true
                become_user: root

              hosts:
                instance-1:
                  config:
                    advertise_uri: 'vm1:3301'
                    http_port: 8081

            host2:
              vars:
                ansible_host: vm2
                ansible_user: root
                ansible_connection: docker
                become: true
                become_user: root

              hosts:
                instance-2:
                  config:
                    advertise_uri: 'vm2:3311'
                    http_port: 8091

                instance-3:
                  config:
                    advertise_uri: 'vm2:3312'
                    http_port: 8092
