---
all:
  children:
    cluster:
      vars:
        cartridge_app_name: myapp
        cartridge_package_path: ./myapp-1.0.0-0.rpm
        cartridge_cluster_cookie: new-cookie
        cartridge_defaults:
          log_level: 1

      children:
        storage_1_replicaset:
          hosts:
            storage-1:
            storage-1-replica:
            storage-1-replica-2:
          vars:
            replicaset_name: storage-1
            leader: storage-1
            roles:
              - 'vshard-storage'

        core_1_replicaset:
          hosts:
            core-1:

          vars:
            replicaset_name: core-1
            leader: core-1
            roles:
              - 'app.roles.custom'
              - 'vshard-router'

        host1:
          vars:
            ansible_host: vm1
            ansible_user: root
            ansible_connection: docker
            become: true
            become_user: root

          hosts:
            storage-1:
              config:
                advertise_uri: 'vm1:3301'
                http_port: 8081

            storage-1-replica:
              config:
                advertise_uri: 'vm1:3302'
                http_port: 8082

        host2:
          vars:
            ansible_host: vm2
            ansible_user: root
            ansible_connection: docker
            become: true
            become_user: root

          hosts:
            core-1:
              config:
                advertise_uri: 'vm2:3311'
                http_port: 8091

            storage-1-replica-2:
              config:
                advertise_uri: 'vm2:3312'
                http_port: 8092
