---
dependency:
  name: galaxy

driver:
  name: docker

create:

platforms:
  - name: vm1
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 127.0.0.1:8081:8081/tcp
      - 127.0.0.1:8082:8082/tcp
    networks:
      - name: cartridge-network
    purge_networks: true
  - name: vm2
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 127.0.0.1:8083:8083/tcp
      - 127.0.0.1:8084:8084/tcp
    networks:
      - name: cartridge-network
    purge_networks: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        cartridge_package_path: ./myapp-1.0.0-0.rpm

        cartridge_config_defaults:
          cluster_cookie: app-default-cookie

    host_vars:
      vm1:
        cartridge_config:
          instances:
            - name: 'core_1'
              advertise_uri: '3301'
              http_port: '8081'
              roles: ['app.roles.custom']

            - name: 'storage_1'
              advertise_uri: '3302'
              http_port: '8082'
              roles: ['vshard-storage']
      vm2:
        cartridge_config:
          instances:
            - name: 'core_2'
              advertise_uri: '3303'
              http_port: '8083'
              roles: ['app.roles.custom']

            - name: 'storage_1_replica'
              advertise_uri: '3304'
              http_port: '8084'
              replica_for: 'storage_1'

verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: E501
