---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vm1
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8081-8090:8081-8090/tcp
    networks:
      - name: cartridge-network
  - name: vm2
    image: jrei/systemd-ubuntu:18.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8091-8099:8091-8099/tcp
    networks:
      - name: cartridge-network
    privileged: true
  - name: vm3
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8071-8080:8071-8080/tcp
    networks:
      - name: cartridge-network
    purge_networks: true
    env:
      TARANTOOL_VERSION: $TARANTOOL_VERSION

lint: |
  set -xe
  yamllint .
  flake8 library molecule/default/tests

provisioner:
  name: ansible
  inventory:
    links:
      hosts: hosts.yml

verifier:
  name: testinfra
  options:
    v: true
