---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vm1
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8081-8090:8081-8090/tcp
    networks:
      - name: cartridge-network
    purge_networks: true
  - name: vm2
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8091-8099:8091-8099/tcp
    networks:
      - name: cartridge-network
    purge_networks: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        cartridge_package_path: ./myapp-1.0.0-0.rpm

        cartridge_config_defaults:
          cluster_cookie: app-default-cookie

    host_vars:
      vm1:
        cartridge_config:
          instances:
            - name: 'core_1'
              advertise_uri: '3301'
              http_port: '8081'
              roles: ['app.roles.custom']

            - name: 'storage_1'
              advertise_uri: '3302'
              http_port: '8082'
              roles: ['vshard-storage']

            - name: 'storage_2_replica'
              advertise_uri: '3303'
              http_port: '8083'
              replica_for: 'storage_2_alias'
      vm2:
        cartridge_config:
          instances:
            - name: 'router_1'
              advertise_uri: '3311'
              http_port: '8091'
              roles: ['vshard-router']

            - name: 'storage_1_replica'
              advertise_uri: '3312'
              http_port: '8092'
              replica_for: 'storage_1'

            - name: 'core_2'
              advertise_uri: '3313'
              http_port: '8093'

            - name: 'storage_2'
              advertise_uri: '3314'
              http_port: '8094'
              alias: 'storage_2_alias'
              roles: ['vshard-storage']

verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: E501
