---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vm1
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: vm2
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        cartridge_package_path: ./myapp-1.0.0-0.rpm

        cartridge_config_defaults:
          cluster_cookie: app-default-cookie

    host_vars:
      vm1:
        cartridge_config_defaults:
          cluster_cookie: this-server-default-cookie

        cartridge_config:
          instances:
            - name: 'core_1'
              advertise_uri: '3000'
              http_port: '8080'
              roles: ['app.roles.custom']

            - name: 'storage_1'
              advertise_uri: 'localhost:3002'
              http_port: '8082'
              roles: ['vshard-storage']
      vm2:
        cartridge_config:
          instances:
            - name: 'core_2'
              advertise_uri: '3004'
              http_port: '8084'
              roles: ['app.roles.custom']

            - name: 'storage_1_replica'
              advertise_uri: '3005'
              http_port: '8085'
              replica_for: 'storage_1'

verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: E501
