---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vm1
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8101-8199:8101-8199/tcp
    networks:
      - name: cartridge-network
  - name: vm2
    image: jrei/systemd-ubuntu:18.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8201-8299:8201-8299/tcp
    networks:
      - name: cartridge-network
    privileged: true
  - name: vm3
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8301-8399:8301-8399/tcp
    networks:
      - name: cartridge-network
  - name: vm4
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 8401-8499:8401-8499/tcp
    networks:
      - name: cartridge-network

lint: |
  set -xe
  yamllint .
  flake8 library molecule/default/tests

provisioner:
  name: ansible
  inventory:
    links:
      hosts: hosts.yml

verifier:
  name: testinfra
  options:
    v: true

scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
