---
- name: Deploy my Tarantool Cartridge app
  hosts: all
  become: true
  become_user: root
  vars:
    cartridge_custom_steps_dir: "custom_steps"
    cartridge_custom_steps:
      - name: my_restart
        file: "../common/my_restart.yml"
      - name: deliver_package
        file: "../common/load_package_from_server.yml"

  tasks:
    - name: Install package of Tarantool Cartridge
      import_role:
        name: tarantool-cartridge
      vars:
        cartridge_scenario:
          - deliver_package
          - install_package
          - configure_systemd_config
          - my_restart

    - name: Make replicasets
      import_role:
        name: tarantool-cartridge
      vars:
        cartridge_scenario:
          - connect_to_membership
          - edit_topology
          - cleanup_expelled

    - name: Config
      import_role:
        name: tarantool-cartridge
      vars:
        cartridge_scenario:
          - configure_auth
          - configure_app_config
          - bootstrap_vshard
          - manage_failover
