boxes = [
    {
        :name     => "vm1",
        :ip => "172.19.0.2",
        :ports    => [8181],
    },
    {
        :name     => "vm2",
        :ip => "172.19.0.3",
        :ports    => [8182, 8183],
    },
]

$script = <<SCRIPT
yum -y install epel-release
yum -y install supervisor
systemctl start supervisord
systemctl enable supervisord
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  # Base Vagrant VM configuration
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Configure all VMs
  boxes.each_with_index do |box, index|
    config.vm.define box[:name] do |box_config|
      box_config.vm.hostname = box[:hostname]
      box_config.vm.network "private_network", ip: box[:ip]
      box[:ports].each do |port|
        box_config.vm.network "forwarded_port",
                              guest: port,
                              host: port,
                              autocorrect: true
      end
    end
  end

  config.vm.provision "shell", inline: $script
end
