---

cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp

    cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

  # instances
  hosts:
    instance-started:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    instance-stopped:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

    instance-restarted:
      config:
        advertise_uri: 'vm1:3103'
        http_port: 8103

    instance-restarted-force:
      config:
        advertise_uri: 'vm1:3104'
        http_port: 8104

  children:
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        instance-started:
        instance-stopped:
        instance-restarted:
        instance-restarted-force:

    replicaset_1:
      vars:
        replicaset_alias: r-1
        roles: []

      hosts:
        instance-started:
        instance-stopped:
        instance-restarted:
        instance-restarted-force:
