---

- name: 'Configure instances'
  hosts: cluster
  roles:
    - ansible-cartridge
  become: true
  become_user: root
  gather_facts: false
  vars:
    cartridge_cluster_cookie: secret-cookie
    cartridge_scenario:
      - deliver_package
      - update_package
      - update_instance
      - configure_instance
