---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: myapp

    cartridge_cluster_cookie: 'some-cookie-from-inventory'
    set_cluster_cookie_in_config: false

    cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

    cartridge_auth:
      enabled: true

  # instances
  hosts:
    instance-1:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    instance-2:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        instance-1:
        instance-2:

    replicaset_1:
      vars:
        replicaset_alias: rpl-1

      hosts:
        instance-1:
        instance-2:
