---

all:
  children:
    cluster:
      vars:
        ansible_user: root
        ansible_connection: docker
        become: true
        become_user: root

        cartridge_app_name: myapp
        cartridge_cluster_cookie: secret-cookie
        cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

        cartridge_failover_params:
          mode: stateful
          state_provider: stateboard
          stateboard_params:
            uri: vm1:4001
            password: secret-stateboard

      hosts:
        my-stateboard:
          config:
            listen: 0.0.0.0:4001
            password: secret-stateboard
          stateboard: true

        core-1:
          replicaset_alias: core
          config:
            advertise_uri: 'vm1:3301'
            http_port: 8101

        core-2:
          replicaset_alias: core
          config:
            advertise_uri: 'vm1:3302'
            http_port: 8102

        core-3:
          config:
            advertise_uri: 'vm1:3303'
            http_port: 8103

      children:
        machine_1:
          vars:
            ansible_host: vm1

          hosts:
            my-stateboard:
            core-1:
            core-2:
            core-3:

        core_replicaset:
          hosts:
            core-1:
            core-2:
            core-3:
          vars:
            failover_priority:
              - core-1
              - core-2
            roles:
              - app.roles.custom
              - vshard-router
              - failover-coordinator
