---
cluster:
  vars:
    # common connection opts
    ansible_user: root
    ansible_connection: docker
    become: true
    become_user: root

    # common cartridge opts
    cartridge_app_name: some-app-name
    cartridge_cluster_cookie: secret-cookie

    cartridge_package_path: ./packages/myapp-1.0.0-0.tar.gz

    cartridge_multiversion: true
    cartridge_bootstrap_vshard: true

  # instances
  hosts:
    core-1:
      config:
        advertise_uri: 'vm1:3101'
        http_port: 8101

    storage-1:
      config:
        advertise_uri: 'vm1:3102'
        http_port: 8102

    my-stateboard:
      config:
        listen: 0.0.0.0:4001
        password: secret-stateboard
      stateboard: true

  children:
    # group by hosts
    machine_1:
      vars:
        ansible_host: vm1

      hosts:
        core-1:
        storage-1:
        my-stateboard:

    # group by replica sets
    core_1_replicaset:
      hosts:
        core-1:
      vars:
        replicaset_alias: core-1
        roles:
          - vshard-router
          - failover-coordinator

    storage_1_replicaset:
      hosts:
        storage-1:
      vars:
        replicaset_alias: storage-1
        roles:
          - vshard-storage
        vshard_group: hot
